### ISSUE TITLE
error: (CC::Analyzer::Engine::EngineFailure) engine coffeelint failed with status 1 and stderr

### ISSUE THREAD

**Issue by jacindaz** [codeclimate/codeclimate-coffeelint#7]
When I run `codeclimate analyze`, with only the coffelint engine enabled I get the following error:

```
>>>> codeclimate analyze
Starting analysis
Running coffeelint: Done!
error: (CC::Analyzer::Engine::EngineFailure) engine coffeelint failed with status 1 and stderr
path.js:439
      throw new TypeError('Arguments to path.resolve must be strings');
            ^
TypeError: Arguments to path.resolve must be strings
  at Object.posix.resolve (path.js:439:13)
  at Object.realpathSync (fs.js:1325:18)
  at read (/usr/lib/node_modules/coffeelint/lib/commandline.js:60:19)
  at readConfigFile (/usr/lib/node_modules/coffeelint/lib/commandline.js:104:12)
  at loadConfig (/usr/lib/node_modules/coffeelint/lib/commandline.js:116:18)
  at Object.<anonymous> (/usr/lib/node_modules/coffeelint/lib/commandline.js:218:14)
  at Object.<anonymous> (/usr/lib/node_modules/coffeelint/lib/commandline.js:244:4)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/usr/lib/node_modules/coffeelint/bin/coffeelint:34:5)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3

/usr/lib/ruby/gems/2.2.0/gems/json-1.8.3/lib/json/common.rb:155:in `initialize': A JSON text must at least contain two octets! (JSON::ParserError)
    from /usr/lib/ruby/gems/2.2.0/gems/json-1.8.3/lib/json/common.rb:155:in `new'
    from /usr/lib/ruby/gems/2.2.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
    from /usr/src/app/lib/cc/engine/coffeelint_results.rb:14:in `block in results'
    from /usr/src/app/lib/cc/engine/coffeelint_results.rb:13:in `chdir'
    from /usr/src/app/lib/cc/engine/coffeelint_results.rb:13:in `results'
    from /usr/src/app/lib/cc/engine/coffeelint.rb:50:in `coffeelint_results'
    from /usr/src/app/lib/cc/engine/coffeelint.rb:14:in `run'
    from /usr/src/app/bin/coffeelint:14:in `<main>'
```

Any idea what might be happening? Thanks!

**Comment by gdiggs** [comment]
@jacindaz Sorry about that! Can you share your `.codeclimate.yml` file?

**Comment by jacindaz** [comment]
```
>>>> cat .codeclimate.yml
---
engines:
  rubocop:
    enabled: false
  golint:
    enabled: false
  gofmt:
    enabled: false
  eslint:
    enabled: false
  csslint:
    enabled: false
  coffeelint:
    enabled: true
    config:
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
exclude_paths:
- log/*
- tmp/*
- vendor/**/*
```

Also: 

``````
>>>> codeclimate engines:install
Pulling docker images.
Pulling repository docker.io/codeclimate/codeclimate-coffeelint
FATA[0000] Error while pulling image: Get https://index.docker.io/v1/repositories/codeclimate/codeclimate-coffeelint/images: dial tcp: lookup index.docker.io on 75.75.76.76:53: server misbehaving
error: (CC::CLI::Engines::Install::ImagePullFailure) unable to pull image codeclimate/codeclimate-coffeelint```
``````

**Comment by gdiggs** [comment]
@jacindaz thanks! For the issue with `engines:install` - sometimes docker loses network connectivity on OS X. Can you try restarting the VM and running `engines:install` again?

**Comment by jacindaz** [comment]
Awesome, thanks. I was able to restart my docker machine and successfully run `codeclimate engines:install`. However, when I only have the coffeelint engine enabled, I get the same error as before.

```
>>>> codeclimate analyze
Starting analysis
Running coffeelint: Done!
error: (CC::Analyzer::Engine::EngineFailure) engine coffeelint failed with status 1 and stderr
path.js:439
      throw new TypeError('Arguments to path.resolve must be strings');
            ^
TypeError: Arguments to path.resolve must be strings
  at Object.posix.resolve (path.js:439:13)
  at Object.realpathSync (fs.js:1325:18)
  at read (/usr/lib/node_modules/coffeelint/lib/commandline.js:60:19)
  at readConfigFile (/usr/lib/node_modules/coffeelint/lib/commandline.js:104:12)
  at loadConfig (/usr/lib/node_modules/coffeelint/lib/commandline.js:116:18)
  at Object.<anonymous> (/usr/lib/node_modules/coffeelint/lib/commandline.js:218:14)
  at Object.<anonymous> (/usr/lib/node_modules/coffeelint/lib/commandline.js:244:4)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/usr/lib/node_modules/coffeelint/bin/coffeelint:34:5)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3

/usr/lib/ruby/gems/2.2.0/gems/json-1.8.3/lib/json/common.rb:155:in `initialize': A JSON text must at least contain two octets! (JSON::ParserError)
    from /usr/lib/ruby/gems/2.2.0/gems/json-1.8.3/lib/json/common.rb:155:in `new'
    from /usr/lib/ruby/gems/2.2.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
    from /usr/src/app/lib/cc/engine/coffeelint_results.rb:14:in `block in results'
    from /usr/src/app/lib/cc/engine/coffeelint_results.rb:13:in `chdir'
    from /usr/src/app/lib/cc/engine/coffeelint_results.rb:13:in `results'
    from /usr/src/app/lib/cc/engine/coffeelint.rb:50:in `coffeelint_results'
    from /usr/src/app/lib/cc/engine/coffeelint.rb:14:in `run'
    from /usr/src/app/bin/coffeelint:14:in `<main>'
```

**Comment by gdiggs** [comment]
@jacindaz ok - it looks like that empty `config:` entry in your yml file is causing the trouble. Can you try removing it and see if that resolves the issue?

**Comment by jacindaz** [comment]
Oh, awesome! That worked. I added the engine via codeclimate engines:enable coffeelint, so I'm not sure if that command is generating the config: line in my yaml file.

**Comment by gdiggs** [comment]
@jacindaz interesting - thanks for that info! We will look into that
